Fixing the sign the published Docker image

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -87,12 +87,25 @@ jobs:
       # repository is public to avoid leaking data.  If you would like to publish
       # transparency data even for private images, pass --force to cosign below.
       # https://github.com/sigstore/cosign
-      - name: Sign the published Docker image
+      - name: Sign the published Docker image with retries
         if: ${{ github.event_name != 'pull_request' }}
         env:
-          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
           TAGS: ${{ steps.meta.outputs.tags }}
           DIGEST: ${{ steps.build-and-push.outputs.digest }}
-        # This step uses the identity token to provision an ephemeral certificate
-        # against the sigstore community Fulcio instance.
-        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
+        run: |
+          max_attempts=3
+          delay_seconds=10
+          attempt=1
+          while true; do
+            echo "Attempt $attempt of $max_attempts"
+            if echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}; then
+              break
+            elif [[ $attempt -lt $max_attempts ]]; then
+              echo "Retry in $delay_seconds seconds..."
+              sleep $delay_seconds
+              ((attempt++))
+            else
+              echo "Failed after $max_attempts attempts."
+              exit 1
+            fi
+          done
